name = "TestPackage"
uuid = "b46ff10a-22a9-4faa-b966-a2e962f972e3"
authors = ["Daniel Holleufer <daniel.holleufer@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"
